export const CHECKOUT_COUNTRIES = [
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "Germany",
  "France",
  "Netherlands",
  "Spain",
  "Italy",
  "Sweden",
  "Norway",
  "Denmark",
  "Switzerland",
  "Ireland",
  "Belgium",
  "Austria",
  "Portugal",
  "Poland",
  "India",
  "Pakistan",
  "United Arab Emirates",
  "Singapore",
  "Japan",
  "South Korea",
  "Brazil",
  "Mexico",
  "New Zealand",
  "South Africa",
] as const;
